[package]
authors = ["Dean Karn <dean.karn@gmail.com>"]
name = "mandlebrot"
version = "0.1.0"

[dependencies]
futures = "0.1.17"
futures-cpupool = "0.1.8"
hyper = "0.11.15"
image = "0.18.0"
num_cpus = "1.8.0"
